# Generated by Django 3.2 on 2023-01-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre completo'),
        ),
    ]
